=== AndresTcharro/ExamenTELenguajes/XML_XSD/informacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">



<!-- Elemeto Padre (informacion) con su atributo y contiene comunidades que pueden aparecer o no  -->
<!-- ............................................................................................. -->
<xs:element name="informacion">
    <xs:complexType>
        <xs:sequence>
            <xs:element ref="comunidades" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="NIF" type="xs:string" use="required"/>
    </xs:complexType>
</xs:element>

<!-- Hijo de informacion que puede aparecer como minimo 0(no existir) o varias veces -->
<!-- .......................................................................................................... -->
<xs:element name="comunidades" >
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element ref="provincias" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
</xs:element>



<!-- Provincias perteneciente a comunidades, el elemento provincias con mínimo 1 y máximo de ocurrencias las que quiera el ususario  -->
<!-- ........................................................................................................ -->
<xs:element name="provincias">
    <xs:complexType>
        <xs:sequence>

            <xs:element name="nombre" type="xs:string"/>
            <xs:element ref="poblaciones" minOccurs="1" maxOccurs="unbounded"/> 
           
        </xs:sequence>
    </xs:complexType>
</xs:element>

<!-- Poblaciones  perteneciente a PROVINCIAS, el elemento provincias con mínimo 1 y máximo de ocurrencias  -->
<!-- ........................................................................................................ -->
<xs:element name="poblaciones">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element ref="prediccion" />
        </xs:sequence>
    </xs:complexType>
</xs:element>
    

                
<!-- Predicion  contiene varios elementos complejos que asu vez contienen elementos simples  / hijo de poblaciones-->
<!-- ......................................................................................................... -->
<xs:element name="prediccion">
<xs:complexType>
        <xs:sequence>

<xs:element name="fecha" type="xs:date"/>
<xs:element name="temperatura_max">
    <xs:simpleType>
        <xs:restriction base="xs:positiveInteger">
            <xs:maxExclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>    
<xs:element name="temperatura_min" >
    <xs:simpleType>
        <xs:restriction base="xs:negativeInteger">
            <xs:minExclusive value="-100"/>
        </xs:restriction>
    </xs:simpleType>
 </xs:element>   
<xs:element name="probabilidad_lluvia" type="xs:string"/>
<xs:element name="aviso">
    <xs:simpleType>
<!-- En la etiqueta categoria le indicamos que solo queremos que sean posibles entres estas tres opciones -->
        <xs:restriction base="xs:string">
            <xs:enumeration value="viento"/>
            <xs:enumeration value="nieve"/>
            <xs:enumeration value="tormentas"/>
            <xs:enumeration value="huracán"/>
        </xs:restriction>
    </xs:simpleType>
</xs:element>   
 
</xs:sequence>
<!-- atributi al cual le indicamos que puede o no aparecer pero si aparece tiene que aparecer con el numero 2 que le indicamos -->
<xs:attribute name="id" type="xs:int" />
</xs:complexType>
</xs:element>

<!-- ........................................................................................................... -->
</xs:schema>

=== AndresTcharro/ExamenTELenguajes/XML_XSD/infomacion.xml
<?xml version="1.0" encoding="UTF-8"?>
<informacion NIF="A -3900001- 3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="./informacion.xsd">

<comunidades>
    <nombre></nombre>
    <provincias >
        <nombre></nombre>
        <poblaciones>
            <nombre></nombre>
            <prediccion id="001">
                <fecha></fecha>
                <temperatura_max></temperatura_max>
                <temperatura_min></temperatura_min>
                <probabilidad_lluvia></probabilidad_lluvia>
                <aviso></aviso>
            </prediccion>
        </poblaciones>
    </provincias>
</comunidades>
</informacion>
